apiVersion: skaffold/v1
kind: Config
metadata:
  name: tftpdd
profiles:
  - name: tftpdd
    build:
      artifacts:
        - image: pojntfx/tftpdd
          context: .
          docker:
            dockerfile: Dockerfile.tftpdd
            buildArgs:
              DIBS_TARGET: tftpdd-linux
      local:
        useBuildkit: true
    deploy:
      helm:
        releases:
          - name: tftpdd
            chartPath: charts/tftpdd
            values:
              meta.image: pojntfx/tftpdd
  - name: tftpdd-dev
    build:
      artifacts:
        - image: pojntfx/tftpdd-dev
          context: .
          docker:
            dockerfile: Dockerfile.dev
            buildArgs:
              DIBS_TARGET: tftpdd-linux
          sync:
            infer:
              - "**/*" # Re-deploy manually to apply k8s changes
      local:
        useBuildkit: true
    deploy:
      helm:
        releases:
          - name: tftpdd-dev
            chartPath: charts/tftpdd
            values:
              meta.image: pojntfx/tftpdd-dev
            setValues:
              meta.dev: true
              meta.target: tftpdd-linux
            setValueTemplates:
              meta.platform: "{{ .TARGETPLATFORM }}"
              meta.debug: "{{ .DIBS_DEBUG }}"
