apiVersion: v1
name: tftpdd
version: 0.0.1
description: A TFTP server management daemon.
type: application
home: https://pojntfx.github.io/tftpdd/
sources:
  - git@github.com:pojntfx/tftpdd.git
maintainers:
  - name: Felix Pojtinger
    email: felix@pojtinger.com
    url: https://felix.pojtinger.com
appVersion: 0.0.1
